"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DomainStatus(_DomainStatus, metaclass=_DomainStatusEnumTypeWrapper):
    pass
class _DomainStatus:
    V = typing.NewType('V', builtins.int)
class _DomainStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DomainStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    DOMAIN_STATUS_INVALID = DomainStatus.V(0)
    DOMAIN_STATUS_REGISTERED = DomainStatus.V(1)
    DOMAIN_STATUS_DEPRECATED = DomainStatus.V(2)
    DOMAIN_STATUS_DELETED = DomainStatus.V(3)

DOMAIN_STATUS_INVALID = DomainStatus.V(0)
DOMAIN_STATUS_REGISTERED = DomainStatus.V(1)
DOMAIN_STATUS_DEPRECATED = DomainStatus.V(2)
DOMAIN_STATUS_DELETED = DomainStatus.V(3)
global___DomainStatus = DomainStatus


class ArchivalStatus(_ArchivalStatus, metaclass=_ArchivalStatusEnumTypeWrapper):
    pass
class _ArchivalStatus:
    V = typing.NewType('V', builtins.int)
class _ArchivalStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ArchivalStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ARCHIVAL_STATUS_INVALID = ArchivalStatus.V(0)
    ARCHIVAL_STATUS_DISABLED = ArchivalStatus.V(1)
    ARCHIVAL_STATUS_ENABLED = ArchivalStatus.V(2)

ARCHIVAL_STATUS_INVALID = ArchivalStatus.V(0)
ARCHIVAL_STATUS_DISABLED = ArchivalStatus.V(1)
ARCHIVAL_STATUS_ENABLED = ArchivalStatus.V(2)
global___ArchivalStatus = ArchivalStatus


class Domain(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    OWNER_EMAIL_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    WORKFLOW_EXECUTION_RETENTION_PERIOD_FIELD_NUMBER: builtins.int
    BAD_BINARIES_FIELD_NUMBER: builtins.int
    HISTORY_ARCHIVAL_STATUS_FIELD_NUMBER: builtins.int
    HISTORY_ARCHIVAL_URI_FIELD_NUMBER: builtins.int
    VISIBILITY_ARCHIVAL_STATUS_FIELD_NUMBER: builtins.int
    VISIBILITY_ARCHIVAL_URI_FIELD_NUMBER: builtins.int
    ACTIVE_CLUSTER_NAME_FIELD_NUMBER: builtins.int
    CLUSTERS_FIELD_NUMBER: builtins.int
    FAILOVER_VERSION_FIELD_NUMBER: builtins.int
    IS_GLOBAL_DOMAIN_FIELD_NUMBER: builtins.int
    FAILOVER_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    name: typing.Text = ...
    status: global___DomainStatus.V = ...
    description: typing.Text = ...
    owner_email: typing.Text = ...
    @property
    def data(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    @property
    def workflow_execution_retention_period(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def bad_binaries(self) -> global___BadBinaries: ...
    history_archival_status: global___ArchivalStatus.V = ...
    history_archival_uri: typing.Text = ...
    visibility_archival_status: global___ArchivalStatus.V = ...
    visibility_archival_uri: typing.Text = ...
    active_cluster_name: typing.Text = ...
    @property
    def clusters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClusterReplicationConfiguration]: ...
    failover_version: builtins.int = ...
    is_global_domain: builtins.bool = ...
    @property
    def failover_info(self) -> global___FailoverInfo: ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        status : global___DomainStatus.V = ...,
        description : typing.Text = ...,
        owner_email : typing.Text = ...,
        data : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        workflow_execution_retention_period : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        bad_binaries : typing.Optional[global___BadBinaries] = ...,
        history_archival_status : global___ArchivalStatus.V = ...,
        history_archival_uri : typing.Text = ...,
        visibility_archival_status : global___ArchivalStatus.V = ...,
        visibility_archival_uri : typing.Text = ...,
        active_cluster_name : typing.Text = ...,
        clusters : typing.Optional[typing.Iterable[global___ClusterReplicationConfiguration]] = ...,
        failover_version : builtins.int = ...,
        is_global_domain : builtins.bool = ...,
        failover_info : typing.Optional[global___FailoverInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bad_binaries",b"bad_binaries","failover_info",b"failover_info","workflow_execution_retention_period",b"workflow_execution_retention_period"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_cluster_name",b"active_cluster_name","bad_binaries",b"bad_binaries","clusters",b"clusters","data",b"data","description",b"description","failover_info",b"failover_info","failover_version",b"failover_version","history_archival_status",b"history_archival_status","history_archival_uri",b"history_archival_uri","id",b"id","is_global_domain",b"is_global_domain","name",b"name","owner_email",b"owner_email","status",b"status","visibility_archival_status",b"visibility_archival_status","visibility_archival_uri",b"visibility_archival_uri","workflow_execution_retention_period",b"workflow_execution_retention_period"]) -> None: ...
global___Domain = Domain

class ClusterReplicationConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CLUSTER_NAME_FIELD_NUMBER: builtins.int
    cluster_name: typing.Text = ...
    def __init__(self,
        *,
        cluster_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cluster_name",b"cluster_name"]) -> None: ...
global___ClusterReplicationConfiguration = ClusterReplicationConfiguration

class BadBinaries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class BinariesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        @property
        def value(self) -> global___BadBinaryInfo: ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Optional[global___BadBinaryInfo] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    BINARIES_FIELD_NUMBER: builtins.int
    @property
    def binaries(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___BadBinaryInfo]: ...
    def __init__(self,
        *,
        binaries : typing.Optional[typing.Mapping[typing.Text, global___BadBinaryInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["binaries",b"binaries"]) -> None: ...
global___BadBinaries = BadBinaries

class BadBinaryInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REASON_FIELD_NUMBER: builtins.int
    OPERATOR_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    reason: typing.Text = ...
    operator: typing.Text = ...
    @property
    def created_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        reason : typing.Text = ...,
        operator : typing.Text = ...,
        created_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_time",b"created_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_time",b"created_time","operator",b"operator","reason",b"reason"]) -> None: ...
global___BadBinaryInfo = BadBinaryInfo

class FailoverInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FAILOVER_VERSION_FIELD_NUMBER: builtins.int
    FAILOVER_START_TIMESTAMP_FIELD_NUMBER: builtins.int
    FAILOVER_EXPIRE_TIMESTAMP_FIELD_NUMBER: builtins.int
    COMPLETED_SHARD_COUNT_FIELD_NUMBER: builtins.int
    PENDING_SHARDS_FIELD_NUMBER: builtins.int
    failover_version: builtins.int = ...
    @property
    def failover_start_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def failover_expire_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    completed_shard_count: builtins.int = ...
    @property
    def pending_shards(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        failover_version : builtins.int = ...,
        failover_start_timestamp : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        failover_expire_timestamp : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        completed_shard_count : builtins.int = ...,
        pending_shards : typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["failover_expire_timestamp",b"failover_expire_timestamp","failover_start_timestamp",b"failover_start_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed_shard_count",b"completed_shard_count","failover_expire_timestamp",b"failover_expire_timestamp","failover_start_timestamp",b"failover_start_timestamp","failover_version",b"failover_version","pending_shards",b"pending_shards"]) -> None: ...
global___FailoverInfo = FailoverInfo
