"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions
import uber.cadence.api.v1.common_pb2
import uber.cadence.api.v1.workflow_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class QueryResultType(_QueryResultType, metaclass=_QueryResultTypeEnumTypeWrapper):
    pass
class _QueryResultType:
    V = typing.NewType('V', builtins.int)
class _QueryResultTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QueryResultType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    QUERY_RESULT_TYPE_INVALID = QueryResultType.V(0)
    QUERY_RESULT_TYPE_ANSWERED = QueryResultType.V(1)
    QUERY_RESULT_TYPE_FAILED = QueryResultType.V(2)

QUERY_RESULT_TYPE_INVALID = QueryResultType.V(0)
QUERY_RESULT_TYPE_ANSWERED = QueryResultType.V(1)
QUERY_RESULT_TYPE_FAILED = QueryResultType.V(2)
global___QueryResultType = QueryResultType


class QueryRejectCondition(_QueryRejectCondition, metaclass=_QueryRejectConditionEnumTypeWrapper):
    pass
class _QueryRejectCondition:
    V = typing.NewType('V', builtins.int)
class _QueryRejectConditionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QueryRejectCondition.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    QUERY_REJECT_CONDITION_INVALID = QueryRejectCondition.V(0)
    QUERY_REJECT_CONDITION_NOT_OPEN = QueryRejectCondition.V(1)
    """QUERY_REJECT_CONDITION_NOT_OPEN indicates that query should be rejected if workflow is not open."""

    QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY = QueryRejectCondition.V(2)
    """QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY indicates that query should be rejected if workflow did not complete cleanly."""


QUERY_REJECT_CONDITION_INVALID = QueryRejectCondition.V(0)
QUERY_REJECT_CONDITION_NOT_OPEN = QueryRejectCondition.V(1)
"""QUERY_REJECT_CONDITION_NOT_OPEN indicates that query should be rejected if workflow is not open."""

QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY = QueryRejectCondition.V(2)
"""QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY indicates that query should be rejected if workflow did not complete cleanly."""

global___QueryRejectCondition = QueryRejectCondition


class QueryConsistencyLevel(_QueryConsistencyLevel, metaclass=_QueryConsistencyLevelEnumTypeWrapper):
    pass
class _QueryConsistencyLevel:
    V = typing.NewType('V', builtins.int)
class _QueryConsistencyLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QueryConsistencyLevel.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    QUERY_CONSISTENCY_LEVEL_INVALID = QueryConsistencyLevel.V(0)
    QUERY_CONSISTENCY_LEVEL_EVENTUAL = QueryConsistencyLevel.V(1)
    """EVENTUAL indicates that query should be eventually consistent."""

    QUERY_CONSISTENCY_LEVEL_STRONG = QueryConsistencyLevel.V(2)
    """STRONG indicates that any events that came before query should be reflected in workflow state before running query."""


QUERY_CONSISTENCY_LEVEL_INVALID = QueryConsistencyLevel.V(0)
QUERY_CONSISTENCY_LEVEL_EVENTUAL = QueryConsistencyLevel.V(1)
"""EVENTUAL indicates that query should be eventually consistent."""

QUERY_CONSISTENCY_LEVEL_STRONG = QueryConsistencyLevel.V(2)
"""STRONG indicates that any events that came before query should be reflected in workflow state before running query."""

global___QueryConsistencyLevel = QueryConsistencyLevel


class WorkflowQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    QUERY_TYPE_FIELD_NUMBER: builtins.int
    QUERY_ARGS_FIELD_NUMBER: builtins.int
    query_type: typing.Text = ...
    @property
    def query_args(self) -> uber.cadence.api.v1.common_pb2.Payload: ...
    def __init__(self,
        *,
        query_type : typing.Text = ...,
        query_args : typing.Optional[uber.cadence.api.v1.common_pb2.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["query_args",b"query_args"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["query_args",b"query_args","query_type",b"query_type"]) -> None: ...
global___WorkflowQuery = WorkflowQuery

class WorkflowQueryResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESULT_TYPE_FIELD_NUMBER: builtins.int
    ANSWER_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    result_type: global___QueryResultType.V = ...
    @property
    def answer(self) -> uber.cadence.api.v1.common_pb2.Payload: ...
    error_message: typing.Text = ...
    def __init__(self,
        *,
        result_type : global___QueryResultType.V = ...,
        answer : typing.Optional[uber.cadence.api.v1.common_pb2.Payload] = ...,
        error_message : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["answer",b"answer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["answer",b"answer","error_message",b"error_message","result_type",b"result_type"]) -> None: ...
global___WorkflowQueryResult = WorkflowQueryResult

class QueryRejected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CLOSE_STATUS_FIELD_NUMBER: builtins.int
    close_status: uber.cadence.api.v1.workflow_pb2.WorkflowExecutionCloseStatus.V = ...
    def __init__(self,
        *,
        close_status : uber.cadence.api.v1.workflow_pb2.WorkflowExecutionCloseStatus.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["close_status",b"close_status"]) -> None: ...
global___QueryRejected = QueryRejected
