# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from uber.cadence.api.v1 import service_meta_pb2 as uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2


class MetaAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/uber.cadence.api.v1.MetaAPI/Health',
                request_serializer=uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthResponse.FromString,
                )


class MetaAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetaAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uber.cadence.api.v1.MetaAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetaAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.api.v1.MetaAPI/Health',
            uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthRequest.SerializeToString,
            uber_dot_cadence_dot_api_dot_v1_dot_service__meta__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
