"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TaskListKind(_TaskListKind, metaclass=_TaskListKindEnumTypeWrapper):
    pass
class _TaskListKind:
    V = typing.NewType('V', builtins.int)
class _TaskListKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskListKind.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TASK_LIST_KIND_INVALID = TaskListKind.V(0)
    TASK_LIST_KIND_NORMAL = TaskListKind.V(1)
    TASK_LIST_KIND_STICKY = TaskListKind.V(2)

TASK_LIST_KIND_INVALID = TaskListKind.V(0)
TASK_LIST_KIND_NORMAL = TaskListKind.V(1)
TASK_LIST_KIND_STICKY = TaskListKind.V(2)
global___TaskListKind = TaskListKind


class TaskListType(_TaskListType, metaclass=_TaskListTypeEnumTypeWrapper):
    pass
class _TaskListType:
    V = typing.NewType('V', builtins.int)
class _TaskListTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskListType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TASK_LIST_TYPE_INVALID = TaskListType.V(0)
    TASK_LIST_TYPE_DECISION = TaskListType.V(1)
    TASK_LIST_TYPE_ACTIVITY = TaskListType.V(2)

TASK_LIST_TYPE_INVALID = TaskListType.V(0)
TASK_LIST_TYPE_DECISION = TaskListType.V(1)
TASK_LIST_TYPE_ACTIVITY = TaskListType.V(2)
global___TaskListType = TaskListType


class TaskList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    kind: global___TaskListKind.V = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        kind : global___TaskListKind.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["kind",b"kind","name",b"name"]) -> None: ...
global___TaskList = TaskList

class TaskListMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MAX_TASKS_PER_SECOND_FIELD_NUMBER: builtins.int
    @property
    def max_tasks_per_second(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    def __init__(self,
        *,
        max_tasks_per_second : typing.Optional[google.protobuf.wrappers_pb2.DoubleValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["max_tasks_per_second",b"max_tasks_per_second"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_tasks_per_second",b"max_tasks_per_second"]) -> None: ...
global___TaskListMetadata = TaskListMetadata

class TaskListPartitionMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    OWNER_HOST_NAME_FIELD_NUMBER: builtins.int
    key: typing.Text = ...
    owner_host_name: typing.Text = ...
    def __init__(self,
        *,
        key : typing.Text = ...,
        owner_host_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","owner_host_name",b"owner_host_name"]) -> None: ...
global___TaskListPartitionMetadata = TaskListPartitionMetadata

class TaskListStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BACKLOG_COUNT_HINT_FIELD_NUMBER: builtins.int
    READ_LEVEL_FIELD_NUMBER: builtins.int
    ACK_LEVEL_FIELD_NUMBER: builtins.int
    RATE_PER_SECOND_FIELD_NUMBER: builtins.int
    TASK_ID_BLOCK_FIELD_NUMBER: builtins.int
    backlog_count_hint: builtins.int = ...
    read_level: builtins.int = ...
    ack_level: builtins.int = ...
    rate_per_second: builtins.float = ...
    @property
    def task_id_block(self) -> global___TaskIDBlock: ...
    def __init__(self,
        *,
        backlog_count_hint : builtins.int = ...,
        read_level : builtins.int = ...,
        ack_level : builtins.int = ...,
        rate_per_second : builtins.float = ...,
        task_id_block : typing.Optional[global___TaskIDBlock] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["task_id_block",b"task_id_block"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ack_level",b"ack_level","backlog_count_hint",b"backlog_count_hint","rate_per_second",b"rate_per_second","read_level",b"read_level","task_id_block",b"task_id_block"]) -> None: ...
global___TaskListStatus = TaskListStatus

class TaskIDBlock(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    START_ID_FIELD_NUMBER: builtins.int
    END_ID_FIELD_NUMBER: builtins.int
    start_id: builtins.int = ...
    end_id: builtins.int = ...
    def __init__(self,
        *,
        start_id : builtins.int = ...,
        end_id : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_id",b"end_id","start_id",b"start_id"]) -> None: ...
global___TaskIDBlock = TaskIDBlock

class PollerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAST_ACCESS_TIME_FIELD_NUMBER: builtins.int
    IDENTITY_FIELD_NUMBER: builtins.int
    RATE_PER_SECOND_FIELD_NUMBER: builtins.int
    @property
    def last_access_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    identity: typing.Text = ...
    rate_per_second: builtins.float = ...
    def __init__(self,
        *,
        last_access_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        identity : typing.Text = ...,
        rate_per_second : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["last_access_time",b"last_access_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["identity",b"identity","last_access_time",b"last_access_time","rate_per_second",b"rate_per_second"]) -> None: ...
global___PollerInfo = PollerInfo

class StickyExecutionAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WORKER_TASK_LIST_FIELD_NUMBER: builtins.int
    SCHEDULE_TO_START_TIMEOUT_FIELD_NUMBER: builtins.int
    @property
    def worker_task_list(self) -> global___TaskList: ...
    @property
    def schedule_to_start_timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(self,
        *,
        worker_task_list : typing.Optional[global___TaskList] = ...,
        schedule_to_start_timeout : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["schedule_to_start_timeout",b"schedule_to_start_timeout","worker_task_list",b"worker_task_list"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["schedule_to_start_timeout",b"schedule_to_start_timeout","worker_task_list",b"worker_task_list"]) -> None: ...
global___StickyExecutionAttributes = StickyExecutionAttributes
