# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/tasklist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uber/cadence/api/v1/tasklist.proto',
  package='uber.cadence.api.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.uber.cadence.api.v1B\010ApiProtoP\001Z/github.com/uber/cadence/.gen/proto/api/v1;apiv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"uber/cadence/api/v1/tasklist.proto\x12\x13uber.cadence.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"I\n\x08TaskList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x04kind\x18\x02 \x01(\x0e\x32!.uber.cadence.api.v1.TaskListKind\"N\n\x10TaskListMetadata\x12:\n\x14max_tasks_per_second\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"A\n\x19TaskListPartitionMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x0fowner_host_name\x18\x02 \x01(\t\"\xa5\x01\n\x0eTaskListStatus\x12\x1a\n\x12\x62\x61\x63klog_count_hint\x18\x01 \x01(\x03\x12\x12\n\nread_level\x18\x02 \x01(\x03\x12\x11\n\tack_level\x18\x03 \x01(\x03\x12\x17\n\x0frate_per_second\x18\x04 \x01(\x01\x12\x37\n\rtask_id_block\x18\x05 \x01(\x0b\x32 .uber.cadence.api.v1.TaskIDBlock\"/\n\x0bTaskIDBlock\x12\x10\n\x08start_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x65nd_id\x18\x02 \x01(\x03\"m\n\nPollerInfo\x12\x34\n\x10last_access_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x17\n\x0frate_per_second\x18\x03 \x01(\x01\"\x92\x01\n\x19StickyExecutionAttributes\x12\x37\n\x10worker_task_list\x18\x01 \x01(\x0b\x32\x1d.uber.cadence.api.v1.TaskList\x12<\n\x19schedule_to_start_timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration*`\n\x0cTaskListKind\x12\x1a\n\x16TASK_LIST_KIND_INVALID\x10\x00\x12\x19\n\x15TASK_LIST_KIND_NORMAL\x10\x01\x12\x19\n\x15TASK_LIST_KIND_STICKY\x10\x02*d\n\x0cTaskListType\x12\x1a\n\x16TASK_LIST_TYPE_INVALID\x10\x00\x12\x1b\n\x17TASK_LIST_TYPE_DECISION\x10\x01\x12\x1b\n\x17TASK_LIST_TYPE_ACTIVITY\x10\x02\x42V\n\x17\x63om.uber.cadence.api.v1B\x08\x41piProtoP\x01Z/github.com/uber/cadence/.gen/proto/api/v1;apiv1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])

_TASKLISTKIND = _descriptor.EnumDescriptor(
  name='TaskListKind',
  full_name='uber.cadence.api.v1.TaskListKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_STICKY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=855,
  serialized_end=951,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTKIND)

TaskListKind = enum_type_wrapper.EnumTypeWrapper(_TASKLISTKIND)
_TASKLISTTYPE = _descriptor.EnumDescriptor(
  name='TaskListType',
  full_name='uber.cadence.api.v1.TaskListType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_DECISION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_ACTIVITY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=953,
  serialized_end=1053,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTTYPE)

TaskListType = enum_type_wrapper.EnumTypeWrapper(_TASKLISTTYPE)
TASK_LIST_KIND_INVALID = 0
TASK_LIST_KIND_NORMAL = 1
TASK_LIST_KIND_STICKY = 2
TASK_LIST_TYPE_INVALID = 0
TASK_LIST_TYPE_DECISION = 1
TASK_LIST_TYPE_ACTIVITY = 2



_TASKLIST = _descriptor.Descriptor(
  name='TaskList',
  full_name='uber.cadence.api.v1.TaskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='uber.cadence.api.v1.TaskList.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kind', full_name='uber.cadence.api.v1.TaskList.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=229,
)


_TASKLISTMETADATA = _descriptor.Descriptor(
  name='TaskListMetadata',
  full_name='uber.cadence.api.v1.TaskListMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_tasks_per_second', full_name='uber.cadence.api.v1.TaskListMetadata.max_tasks_per_second', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=309,
)


_TASKLISTPARTITIONMETADATA = _descriptor.Descriptor(
  name='TaskListPartitionMetadata',
  full_name='uber.cadence.api.v1.TaskListPartitionMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='uber.cadence.api.v1.TaskListPartitionMetadata.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_host_name', full_name='uber.cadence.api.v1.TaskListPartitionMetadata.owner_host_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=376,
)


_TASKLISTSTATUS = _descriptor.Descriptor(
  name='TaskListStatus',
  full_name='uber.cadence.api.v1.TaskListStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='backlog_count_hint', full_name='uber.cadence.api.v1.TaskListStatus.backlog_count_hint', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_level', full_name='uber.cadence.api.v1.TaskListStatus.read_level', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack_level', full_name='uber.cadence.api.v1.TaskListStatus.ack_level', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate_per_second', full_name='uber.cadence.api.v1.TaskListStatus.rate_per_second', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id_block', full_name='uber.cadence.api.v1.TaskListStatus.task_id_block', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=544,
)


_TASKIDBLOCK = _descriptor.Descriptor(
  name='TaskIDBlock',
  full_name='uber.cadence.api.v1.TaskIDBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_id', full_name='uber.cadence.api.v1.TaskIDBlock.start_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_id', full_name='uber.cadence.api.v1.TaskIDBlock.end_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=593,
)


_POLLERINFO = _descriptor.Descriptor(
  name='PollerInfo',
  full_name='uber.cadence.api.v1.PollerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_access_time', full_name='uber.cadence.api.v1.PollerInfo.last_access_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity', full_name='uber.cadence.api.v1.PollerInfo.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate_per_second', full_name='uber.cadence.api.v1.PollerInfo.rate_per_second', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=704,
)


_STICKYEXECUTIONATTRIBUTES = _descriptor.Descriptor(
  name='StickyExecutionAttributes',
  full_name='uber.cadence.api.v1.StickyExecutionAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_task_list', full_name='uber.cadence.api.v1.StickyExecutionAttributes.worker_task_list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schedule_to_start_timeout', full_name='uber.cadence.api.v1.StickyExecutionAttributes.schedule_to_start_timeout', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=853,
)

_TASKLIST.fields_by_name['kind'].enum_type = _TASKLISTKIND
_TASKLISTMETADATA.fields_by_name['max_tasks_per_second'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_TASKLISTSTATUS.fields_by_name['task_id_block'].message_type = _TASKIDBLOCK
_POLLERINFO.fields_by_name['last_access_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STICKYEXECUTIONATTRIBUTES.fields_by_name['worker_task_list'].message_type = _TASKLIST
_STICKYEXECUTIONATTRIBUTES.fields_by_name['schedule_to_start_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['TaskList'] = _TASKLIST
DESCRIPTOR.message_types_by_name['TaskListMetadata'] = _TASKLISTMETADATA
DESCRIPTOR.message_types_by_name['TaskListPartitionMetadata'] = _TASKLISTPARTITIONMETADATA
DESCRIPTOR.message_types_by_name['TaskListStatus'] = _TASKLISTSTATUS
DESCRIPTOR.message_types_by_name['TaskIDBlock'] = _TASKIDBLOCK
DESCRIPTOR.message_types_by_name['PollerInfo'] = _POLLERINFO
DESCRIPTOR.message_types_by_name['StickyExecutionAttributes'] = _STICKYEXECUTIONATTRIBUTES
DESCRIPTOR.enum_types_by_name['TaskListKind'] = _TASKLISTKIND
DESCRIPTOR.enum_types_by_name['TaskListType'] = _TASKLISTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskList = _reflection.GeneratedProtocolMessageType('TaskList', (_message.Message,), {
  'DESCRIPTOR' : _TASKLIST,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.TaskList)
  })
_sym_db.RegisterMessage(TaskList)

TaskListMetadata = _reflection.GeneratedProtocolMessageType('TaskListMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTMETADATA,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.TaskListMetadata)
  })
_sym_db.RegisterMessage(TaskListMetadata)

TaskListPartitionMetadata = _reflection.GeneratedProtocolMessageType('TaskListPartitionMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTPARTITIONMETADATA,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.TaskListPartitionMetadata)
  })
_sym_db.RegisterMessage(TaskListPartitionMetadata)

TaskListStatus = _reflection.GeneratedProtocolMessageType('TaskListStatus', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTSTATUS,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.TaskListStatus)
  })
_sym_db.RegisterMessage(TaskListStatus)

TaskIDBlock = _reflection.GeneratedProtocolMessageType('TaskIDBlock', (_message.Message,), {
  'DESCRIPTOR' : _TASKIDBLOCK,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.TaskIDBlock)
  })
_sym_db.RegisterMessage(TaskIDBlock)

PollerInfo = _reflection.GeneratedProtocolMessageType('PollerInfo', (_message.Message,), {
  'DESCRIPTOR' : _POLLERINFO,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.PollerInfo)
  })
_sym_db.RegisterMessage(PollerInfo)

StickyExecutionAttributes = _reflection.GeneratedProtocolMessageType('StickyExecutionAttributes', (_message.Message,), {
  'DESCRIPTOR' : _STICKYEXECUTIONATTRIBUTES,
  '__module__' : 'uber.cadence.api.v1.tasklist_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.StickyExecutionAttributes)
  })
_sym_db.RegisterMessage(StickyExecutionAttributes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
