"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions
import uber.cadence.api.v1.common_pb2
import uber.cadence.api.v1.tasklist_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class PendingActivityState(_PendingActivityState, metaclass=_PendingActivityStateEnumTypeWrapper):
    pass
class _PendingActivityState:
    V = typing.NewType('V', builtins.int)
class _PendingActivityStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingActivityState.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PENDING_ACTIVITY_STATE_INVALID = PendingActivityState.V(0)
    PENDING_ACTIVITY_STATE_SCHEDULED = PendingActivityState.V(1)
    PENDING_ACTIVITY_STATE_STARTED = PendingActivityState.V(2)
    PENDING_ACTIVITY_STATE_CANCEL_REQUESTED = PendingActivityState.V(3)

PENDING_ACTIVITY_STATE_INVALID = PendingActivityState.V(0)
PENDING_ACTIVITY_STATE_SCHEDULED = PendingActivityState.V(1)
PENDING_ACTIVITY_STATE_STARTED = PendingActivityState.V(2)
PENDING_ACTIVITY_STATE_CANCEL_REQUESTED = PendingActivityState.V(3)
global___PendingActivityState = PendingActivityState


class PendingDecisionState(_PendingDecisionState, metaclass=_PendingDecisionStateEnumTypeWrapper):
    pass
class _PendingDecisionState:
    V = typing.NewType('V', builtins.int)
class _PendingDecisionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingDecisionState.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PENDING_DECISION_STATE_INVALID = PendingDecisionState.V(0)
    PENDING_DECISION_STATE_SCHEDULED = PendingDecisionState.V(1)
    PENDING_DECISION_STATE_STARTED = PendingDecisionState.V(2)

PENDING_DECISION_STATE_INVALID = PendingDecisionState.V(0)
PENDING_DECISION_STATE_SCHEDULED = PendingDecisionState.V(1)
PENDING_DECISION_STATE_STARTED = PendingDecisionState.V(2)
global___PendingDecisionState = PendingDecisionState


class WorkflowIdReusePolicy(_WorkflowIdReusePolicy, metaclass=_WorkflowIdReusePolicyEnumTypeWrapper):
    pass
class _WorkflowIdReusePolicy:
    V = typing.NewType('V', builtins.int)
class _WorkflowIdReusePolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowIdReusePolicy.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    WORKFLOW_ID_REUSE_POLICY_INVALID = WorkflowIdReusePolicy.V(0)
    WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY = WorkflowIdReusePolicy.V(1)
    """Allow start a workflow execution using the same workflow ID,
    when workflow not running, and the last execution close state is in [terminated, cancelled, timeouted, failed].
    """

    WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE = WorkflowIdReusePolicy.V(2)
    """Allow start a workflow execution using the same workflow ID, when workflow not running."""

    WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE = WorkflowIdReusePolicy.V(3)
    """Do not allow start a workflow execution using the same workflow ID at all."""

    WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING = WorkflowIdReusePolicy.V(4)
    """If a workflow is running using the same workflow ID, terminate it and start a new one."""


WORKFLOW_ID_REUSE_POLICY_INVALID = WorkflowIdReusePolicy.V(0)
WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY = WorkflowIdReusePolicy.V(1)
"""Allow start a workflow execution using the same workflow ID,
when workflow not running, and the last execution close state is in [terminated, cancelled, timeouted, failed].
"""

WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE = WorkflowIdReusePolicy.V(2)
"""Allow start a workflow execution using the same workflow ID, when workflow not running."""

WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE = WorkflowIdReusePolicy.V(3)
"""Do not allow start a workflow execution using the same workflow ID at all."""

WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING = WorkflowIdReusePolicy.V(4)
"""If a workflow is running using the same workflow ID, terminate it and start a new one."""

global___WorkflowIdReusePolicy = WorkflowIdReusePolicy


class ParentClosePolicy(_ParentClosePolicy, metaclass=_ParentClosePolicyEnumTypeWrapper):
    pass
class _ParentClosePolicy:
    V = typing.NewType('V', builtins.int)
class _ParentClosePolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ParentClosePolicy.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PARENT_CLOSE_POLICY_INVALID = ParentClosePolicy.V(0)
    PARENT_CLOSE_POLICY_ABANDON = ParentClosePolicy.V(1)
    """Abandon means not doing anything on the child workflow."""

    PARENT_CLOSE_POLICY_REQUEST_CANCEL = ParentClosePolicy.V(2)
    """Cancel means requesting cancellation on the child workflow."""

    PARENT_CLOSE_POLICY_TERMINATE = ParentClosePolicy.V(3)
    """Terminate means terminating the child workflow."""


PARENT_CLOSE_POLICY_INVALID = ParentClosePolicy.V(0)
PARENT_CLOSE_POLICY_ABANDON = ParentClosePolicy.V(1)
"""Abandon means not doing anything on the child workflow."""

PARENT_CLOSE_POLICY_REQUEST_CANCEL = ParentClosePolicy.V(2)
"""Cancel means requesting cancellation on the child workflow."""

PARENT_CLOSE_POLICY_TERMINATE = ParentClosePolicy.V(3)
"""Terminate means terminating the child workflow."""

global___ParentClosePolicy = ParentClosePolicy


class WorkflowExecutionCloseStatus(_WorkflowExecutionCloseStatus, metaclass=_WorkflowExecutionCloseStatusEnumTypeWrapper):
    pass
class _WorkflowExecutionCloseStatus:
    V = typing.NewType('V', builtins.int)
class _WorkflowExecutionCloseStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowExecutionCloseStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    WORKFLOW_EXECUTION_CLOSE_STATUS_INVALID = WorkflowExecutionCloseStatus.V(0)
    WORKFLOW_EXECUTION_CLOSE_STATUS_COMPLETED = WorkflowExecutionCloseStatus.V(1)
    WORKFLOW_EXECUTION_CLOSE_STATUS_FAILED = WorkflowExecutionCloseStatus.V(2)
    WORKFLOW_EXECUTION_CLOSE_STATUS_CANCELED = WorkflowExecutionCloseStatus.V(3)
    WORKFLOW_EXECUTION_CLOSE_STATUS_TERMINATED = WorkflowExecutionCloseStatus.V(4)
    WORKFLOW_EXECUTION_CLOSE_STATUS_CONTINUED_AS_NEW = WorkflowExecutionCloseStatus.V(5)
    WORKFLOW_EXECUTION_CLOSE_STATUS_TIMED_OUT = WorkflowExecutionCloseStatus.V(6)

WORKFLOW_EXECUTION_CLOSE_STATUS_INVALID = WorkflowExecutionCloseStatus.V(0)
WORKFLOW_EXECUTION_CLOSE_STATUS_COMPLETED = WorkflowExecutionCloseStatus.V(1)
WORKFLOW_EXECUTION_CLOSE_STATUS_FAILED = WorkflowExecutionCloseStatus.V(2)
WORKFLOW_EXECUTION_CLOSE_STATUS_CANCELED = WorkflowExecutionCloseStatus.V(3)
WORKFLOW_EXECUTION_CLOSE_STATUS_TERMINATED = WorkflowExecutionCloseStatus.V(4)
WORKFLOW_EXECUTION_CLOSE_STATUS_CONTINUED_AS_NEW = WorkflowExecutionCloseStatus.V(5)
WORKFLOW_EXECUTION_CLOSE_STATUS_TIMED_OUT = WorkflowExecutionCloseStatus.V(6)
global___WorkflowExecutionCloseStatus = WorkflowExecutionCloseStatus


class ContinueAsNewInitiator(_ContinueAsNewInitiator, metaclass=_ContinueAsNewInitiatorEnumTypeWrapper):
    pass
class _ContinueAsNewInitiator:
    V = typing.NewType('V', builtins.int)
class _ContinueAsNewInitiatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContinueAsNewInitiator.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CONTINUE_AS_NEW_INITIATOR_INVALID = ContinueAsNewInitiator.V(0)
    CONTINUE_AS_NEW_INITIATOR_DECIDER = ContinueAsNewInitiator.V(1)
    CONTINUE_AS_NEW_INITIATOR_RETRY_POLICY = ContinueAsNewInitiator.V(2)
    CONTINUE_AS_NEW_INITIATOR_CRON_SCHEDULE = ContinueAsNewInitiator.V(3)

CONTINUE_AS_NEW_INITIATOR_INVALID = ContinueAsNewInitiator.V(0)
CONTINUE_AS_NEW_INITIATOR_DECIDER = ContinueAsNewInitiator.V(1)
CONTINUE_AS_NEW_INITIATOR_RETRY_POLICY = ContinueAsNewInitiator.V(2)
CONTINUE_AS_NEW_INITIATOR_CRON_SCHEDULE = ContinueAsNewInitiator.V(3)
global___ContinueAsNewInitiator = ContinueAsNewInitiator


class TimeoutType(_TimeoutType, metaclass=_TimeoutTypeEnumTypeWrapper):
    pass
class _TimeoutType:
    V = typing.NewType('V', builtins.int)
class _TimeoutTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TimeoutType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TIMEOUT_TYPE_INVALID = TimeoutType.V(0)
    TIMEOUT_TYPE_START_TO_CLOSE = TimeoutType.V(1)
    TIMEOUT_TYPE_SCHEDULE_TO_START = TimeoutType.V(2)
    TIMEOUT_TYPE_SCHEDULE_TO_CLOSE = TimeoutType.V(3)
    TIMEOUT_TYPE_HEARTBEAT = TimeoutType.V(4)

TIMEOUT_TYPE_INVALID = TimeoutType.V(0)
TIMEOUT_TYPE_START_TO_CLOSE = TimeoutType.V(1)
TIMEOUT_TYPE_SCHEDULE_TO_START = TimeoutType.V(2)
TIMEOUT_TYPE_SCHEDULE_TO_CLOSE = TimeoutType.V(3)
TIMEOUT_TYPE_HEARTBEAT = TimeoutType.V(4)
global___TimeoutType = TimeoutType


class DecisionTaskTimedOutCause(_DecisionTaskTimedOutCause, metaclass=_DecisionTaskTimedOutCauseEnumTypeWrapper):
    pass
class _DecisionTaskTimedOutCause:
    V = typing.NewType('V', builtins.int)
class _DecisionTaskTimedOutCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DecisionTaskTimedOutCause.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    DECISION_TASK_TIMED_OUT_CAUSE_INVALID = DecisionTaskTimedOutCause.V(0)
    DECISION_TASK_TIMED_OUT_CAUSE_TIMEOUT = DecisionTaskTimedOutCause.V(1)
    DECISION_TASK_TIMED_OUT_CAUSE_RESET = DecisionTaskTimedOutCause.V(2)

DECISION_TASK_TIMED_OUT_CAUSE_INVALID = DecisionTaskTimedOutCause.V(0)
DECISION_TASK_TIMED_OUT_CAUSE_TIMEOUT = DecisionTaskTimedOutCause.V(1)
DECISION_TASK_TIMED_OUT_CAUSE_RESET = DecisionTaskTimedOutCause.V(2)
global___DecisionTaskTimedOutCause = DecisionTaskTimedOutCause


class DecisionTaskFailedCause(_DecisionTaskFailedCause, metaclass=_DecisionTaskFailedCauseEnumTypeWrapper):
    pass
class _DecisionTaskFailedCause:
    V = typing.NewType('V', builtins.int)
class _DecisionTaskFailedCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DecisionTaskFailedCause.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    DECISION_TASK_FAILED_CAUSE_INVALID = DecisionTaskFailedCause.V(0)
    DECISION_TASK_FAILED_CAUSE_UNHANDLED_DECISION = DecisionTaskFailedCause.V(1)
    DECISION_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES = DecisionTaskFailedCause.V(2)
    DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES = DecisionTaskFailedCause.V(3)
    DECISION_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES = DecisionTaskFailedCause.V(4)
    DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES = DecisionTaskFailedCause.V(5)
    DECISION_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES = DecisionTaskFailedCause.V(6)
    DECISION_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(7)
    DECISION_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(8)
    DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(9)
    DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(10)
    DECISION_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES = DecisionTaskFailedCause.V(11)
    DECISION_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID = DecisionTaskFailedCause.V(12)
    DECISION_TASK_FAILED_CAUSE_RESET_STICKY_TASK_LIST = DecisionTaskFailedCause.V(13)
    DECISION_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE = DecisionTaskFailedCause.V(14)
    DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(15)
    DECISION_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(16)
    DECISION_TASK_FAILED_CAUSE_FORCE_CLOSE_DECISION = DecisionTaskFailedCause.V(17)
    DECISION_TASK_FAILED_CAUSE_FAILOVER_CLOSE_DECISION = DecisionTaskFailedCause.V(18)
    DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE = DecisionTaskFailedCause.V(19)
    DECISION_TASK_FAILED_CAUSE_RESET_WORKFLOW = DecisionTaskFailedCause.V(20)
    DECISION_TASK_FAILED_CAUSE_BAD_BINARY = DecisionTaskFailedCause.V(21)
    DECISION_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID = DecisionTaskFailedCause.V(22)
    DECISION_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES = DecisionTaskFailedCause.V(23)

DECISION_TASK_FAILED_CAUSE_INVALID = DecisionTaskFailedCause.V(0)
DECISION_TASK_FAILED_CAUSE_UNHANDLED_DECISION = DecisionTaskFailedCause.V(1)
DECISION_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES = DecisionTaskFailedCause.V(2)
DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES = DecisionTaskFailedCause.V(3)
DECISION_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES = DecisionTaskFailedCause.V(4)
DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES = DecisionTaskFailedCause.V(5)
DECISION_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES = DecisionTaskFailedCause.V(6)
DECISION_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(7)
DECISION_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(8)
DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(9)
DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(10)
DECISION_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES = DecisionTaskFailedCause.V(11)
DECISION_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID = DecisionTaskFailedCause.V(12)
DECISION_TASK_FAILED_CAUSE_RESET_STICKY_TASK_LIST = DecisionTaskFailedCause.V(13)
DECISION_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE = DecisionTaskFailedCause.V(14)
DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(15)
DECISION_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES = DecisionTaskFailedCause.V(16)
DECISION_TASK_FAILED_CAUSE_FORCE_CLOSE_DECISION = DecisionTaskFailedCause.V(17)
DECISION_TASK_FAILED_CAUSE_FAILOVER_CLOSE_DECISION = DecisionTaskFailedCause.V(18)
DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE = DecisionTaskFailedCause.V(19)
DECISION_TASK_FAILED_CAUSE_RESET_WORKFLOW = DecisionTaskFailedCause.V(20)
DECISION_TASK_FAILED_CAUSE_BAD_BINARY = DecisionTaskFailedCause.V(21)
DECISION_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID = DecisionTaskFailedCause.V(22)
DECISION_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES = DecisionTaskFailedCause.V(23)
global___DecisionTaskFailedCause = DecisionTaskFailedCause


class ChildWorkflowExecutionFailedCause(_ChildWorkflowExecutionFailedCause, metaclass=_ChildWorkflowExecutionFailedCauseEnumTypeWrapper):
    pass
class _ChildWorkflowExecutionFailedCause:
    V = typing.NewType('V', builtins.int)
class _ChildWorkflowExecutionFailedCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChildWorkflowExecutionFailedCause.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = ChildWorkflowExecutionFailedCause.V(0)
    CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_RUNNING = ChildWorkflowExecutionFailedCause.V(1)

CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = ChildWorkflowExecutionFailedCause.V(0)
CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_RUNNING = ChildWorkflowExecutionFailedCause.V(1)
global___ChildWorkflowExecutionFailedCause = ChildWorkflowExecutionFailedCause


class CancelExternalWorkflowExecutionFailedCause(_CancelExternalWorkflowExecutionFailedCause, metaclass=_CancelExternalWorkflowExecutionFailedCauseEnumTypeWrapper):
    pass
class _CancelExternalWorkflowExecutionFailedCause:
    V = typing.NewType('V', builtins.int)
class _CancelExternalWorkflowExecutionFailedCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CancelExternalWorkflowExecutionFailedCause.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = CancelExternalWorkflowExecutionFailedCause.V(0)
    CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = CancelExternalWorkflowExecutionFailedCause.V(1)

CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = CancelExternalWorkflowExecutionFailedCause.V(0)
CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = CancelExternalWorkflowExecutionFailedCause.V(1)
global___CancelExternalWorkflowExecutionFailedCause = CancelExternalWorkflowExecutionFailedCause


class SignalExternalWorkflowExecutionFailedCause(_SignalExternalWorkflowExecutionFailedCause, metaclass=_SignalExternalWorkflowExecutionFailedCauseEnumTypeWrapper):
    pass
class _SignalExternalWorkflowExecutionFailedCause:
    V = typing.NewType('V', builtins.int)
class _SignalExternalWorkflowExecutionFailedCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SignalExternalWorkflowExecutionFailedCause.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = SignalExternalWorkflowExecutionFailedCause.V(0)
    SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = SignalExternalWorkflowExecutionFailedCause.V(1)

SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_INVALID = SignalExternalWorkflowExecutionFailedCause.V(0)
SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = SignalExternalWorkflowExecutionFailedCause.V(1)
global___SignalExternalWorkflowExecutionFailedCause = SignalExternalWorkflowExecutionFailedCause


class WorkflowExecutionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WORKFLOW_EXECUTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    CLOSE_TIME_FIELD_NUMBER: builtins.int
    CLOSE_STATUS_FIELD_NUMBER: builtins.int
    HISTORY_LENGTH_FIELD_NUMBER: builtins.int
    PARENT_EXECUTION_INFO_FIELD_NUMBER: builtins.int
    EXECUTION_TIME_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    SEARCH_ATTRIBUTES_FIELD_NUMBER: builtins.int
    AUTO_RESET_POINTS_FIELD_NUMBER: builtins.int
    TASK_LIST_FIELD_NUMBER: builtins.int
    IS_CRON_FIELD_NUMBER: builtins.int
    @property
    def workflow_execution(self) -> uber.cadence.api.v1.common_pb2.WorkflowExecution: ...
    @property
    def type(self) -> uber.cadence.api.v1.common_pb2.WorkflowType: ...
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def close_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    close_status: global___WorkflowExecutionCloseStatus.V = ...
    history_length: builtins.int = ...
    @property
    def parent_execution_info(self) -> global___ParentExecutionInfo: ...
    @property
    def execution_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def memo(self) -> uber.cadence.api.v1.common_pb2.Memo: ...
    @property
    def search_attributes(self) -> uber.cadence.api.v1.common_pb2.SearchAttributes: ...
    @property
    def auto_reset_points(self) -> global___ResetPoints: ...
    task_list: typing.Text = ...
    is_cron: builtins.bool = ...
    def __init__(self,
        *,
        workflow_execution : typing.Optional[uber.cadence.api.v1.common_pb2.WorkflowExecution] = ...,
        type : typing.Optional[uber.cadence.api.v1.common_pb2.WorkflowType] = ...,
        start_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        close_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        close_status : global___WorkflowExecutionCloseStatus.V = ...,
        history_length : builtins.int = ...,
        parent_execution_info : typing.Optional[global___ParentExecutionInfo] = ...,
        execution_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        memo : typing.Optional[uber.cadence.api.v1.common_pb2.Memo] = ...,
        search_attributes : typing.Optional[uber.cadence.api.v1.common_pb2.SearchAttributes] = ...,
        auto_reset_points : typing.Optional[global___ResetPoints] = ...,
        task_list : typing.Text = ...,
        is_cron : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["auto_reset_points",b"auto_reset_points","close_time",b"close_time","execution_time",b"execution_time","memo",b"memo","parent_execution_info",b"parent_execution_info","search_attributes",b"search_attributes","start_time",b"start_time","type",b"type","workflow_execution",b"workflow_execution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["auto_reset_points",b"auto_reset_points","close_status",b"close_status","close_time",b"close_time","execution_time",b"execution_time","history_length",b"history_length","is_cron",b"is_cron","memo",b"memo","parent_execution_info",b"parent_execution_info","search_attributes",b"search_attributes","start_time",b"start_time","task_list",b"task_list","type",b"type","workflow_execution",b"workflow_execution"]) -> None: ...
global___WorkflowExecutionInfo = WorkflowExecutionInfo

class WorkflowExecutionConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TASK_LIST_FIELD_NUMBER: builtins.int
    EXECUTION_START_TO_CLOSE_TIMEOUT_FIELD_NUMBER: builtins.int
    TASK_START_TO_CLOSE_TIMEOUT_FIELD_NUMBER: builtins.int
    @property
    def task_list(self) -> uber.cadence.api.v1.tasklist_pb2.TaskList: ...
    @property
    def execution_start_to_close_timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def task_start_to_close_timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(self,
        *,
        task_list : typing.Optional[uber.cadence.api.v1.tasklist_pb2.TaskList] = ...,
        execution_start_to_close_timeout : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        task_start_to_close_timeout : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["execution_start_to_close_timeout",b"execution_start_to_close_timeout","task_list",b"task_list","task_start_to_close_timeout",b"task_start_to_close_timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["execution_start_to_close_timeout",b"execution_start_to_close_timeout","task_list",b"task_list","task_start_to_close_timeout",b"task_start_to_close_timeout"]) -> None: ...
global___WorkflowExecutionConfiguration = WorkflowExecutionConfiguration

class ParentExecutionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DOMAIN_ID_FIELD_NUMBER: builtins.int
    DOMAIN_NAME_FIELD_NUMBER: builtins.int
    WORKFLOW_EXECUTION_FIELD_NUMBER: builtins.int
    INITIATED_ID_FIELD_NUMBER: builtins.int
    domain_id: typing.Text = ...
    domain_name: typing.Text = ...
    @property
    def workflow_execution(self) -> uber.cadence.api.v1.common_pb2.WorkflowExecution: ...
    initiated_id: builtins.int = ...
    def __init__(self,
        *,
        domain_id : typing.Text = ...,
        domain_name : typing.Text = ...,
        workflow_execution : typing.Optional[uber.cadence.api.v1.common_pb2.WorkflowExecution] = ...,
        initiated_id : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["workflow_execution",b"workflow_execution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["domain_id",b"domain_id","domain_name",b"domain_name","initiated_id",b"initiated_id","workflow_execution",b"workflow_execution"]) -> None: ...
global___ParentExecutionInfo = ParentExecutionInfo

class ExternalExecutionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WORKFLOW_EXECUTION_FIELD_NUMBER: builtins.int
    INITIATED_ID_FIELD_NUMBER: builtins.int
    @property
    def workflow_execution(self) -> uber.cadence.api.v1.common_pb2.WorkflowExecution: ...
    initiated_id: builtins.int = ...
    def __init__(self,
        *,
        workflow_execution : typing.Optional[uber.cadence.api.v1.common_pb2.WorkflowExecution] = ...,
        initiated_id : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["workflow_execution",b"workflow_execution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["initiated_id",b"initiated_id","workflow_execution",b"workflow_execution"]) -> None: ...
global___ExternalExecutionInfo = ExternalExecutionInfo

class PendingActivityInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ACTIVITY_ID_FIELD_NUMBER: builtins.int
    ACTIVITY_TYPE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    HEARTBEAT_DETAILS_FIELD_NUMBER: builtins.int
    LAST_HEARTBEAT_TIME_FIELD_NUMBER: builtins.int
    LAST_STARTED_TIME_FIELD_NUMBER: builtins.int
    ATTEMPT_FIELD_NUMBER: builtins.int
    MAXIMUM_ATTEMPTS_FIELD_NUMBER: builtins.int
    SCHEDULED_TIME_FIELD_NUMBER: builtins.int
    EXPIRATION_TIME_FIELD_NUMBER: builtins.int
    LAST_FAILURE_FIELD_NUMBER: builtins.int
    LAST_WORKER_IDENTITY_FIELD_NUMBER: builtins.int
    activity_id: typing.Text = ...
    @property
    def activity_type(self) -> uber.cadence.api.v1.common_pb2.ActivityType: ...
    state: global___PendingActivityState.V = ...
    @property
    def heartbeat_details(self) -> uber.cadence.api.v1.common_pb2.Payload: ...
    @property
    def last_heartbeat_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def last_started_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    attempt: builtins.int = ...
    maximum_attempts: builtins.int = ...
    @property
    def scheduled_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expiration_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def last_failure(self) -> uber.cadence.api.v1.common_pb2.Failure: ...
    last_worker_identity: typing.Text = ...
    def __init__(self,
        *,
        activity_id : typing.Text = ...,
        activity_type : typing.Optional[uber.cadence.api.v1.common_pb2.ActivityType] = ...,
        state : global___PendingActivityState.V = ...,
        heartbeat_details : typing.Optional[uber.cadence.api.v1.common_pb2.Payload] = ...,
        last_heartbeat_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_started_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        attempt : builtins.int = ...,
        maximum_attempts : builtins.int = ...,
        scheduled_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        expiration_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_failure : typing.Optional[uber.cadence.api.v1.common_pb2.Failure] = ...,
        last_worker_identity : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["activity_type",b"activity_type","expiration_time",b"expiration_time","heartbeat_details",b"heartbeat_details","last_failure",b"last_failure","last_heartbeat_time",b"last_heartbeat_time","last_started_time",b"last_started_time","scheduled_time",b"scheduled_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["activity_id",b"activity_id","activity_type",b"activity_type","attempt",b"attempt","expiration_time",b"expiration_time","heartbeat_details",b"heartbeat_details","last_failure",b"last_failure","last_heartbeat_time",b"last_heartbeat_time","last_started_time",b"last_started_time","last_worker_identity",b"last_worker_identity","maximum_attempts",b"maximum_attempts","scheduled_time",b"scheduled_time","state",b"state"]) -> None: ...
global___PendingActivityInfo = PendingActivityInfo

class PendingChildExecutionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WORKFLOW_EXECUTION_FIELD_NUMBER: builtins.int
    WORKFLOW_TYPE_NAME_FIELD_NUMBER: builtins.int
    INITIATED_ID_FIELD_NUMBER: builtins.int
    PARENT_CLOSE_POLICY_FIELD_NUMBER: builtins.int
    @property
    def workflow_execution(self) -> uber.cadence.api.v1.common_pb2.WorkflowExecution: ...
    workflow_type_name: typing.Text = ...
    initiated_id: builtins.int = ...
    parent_close_policy: global___ParentClosePolicy.V = ...
    def __init__(self,
        *,
        workflow_execution : typing.Optional[uber.cadence.api.v1.common_pb2.WorkflowExecution] = ...,
        workflow_type_name : typing.Text = ...,
        initiated_id : builtins.int = ...,
        parent_close_policy : global___ParentClosePolicy.V = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["workflow_execution",b"workflow_execution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["initiated_id",b"initiated_id","parent_close_policy",b"parent_close_policy","workflow_execution",b"workflow_execution","workflow_type_name",b"workflow_type_name"]) -> None: ...
global___PendingChildExecutionInfo = PendingChildExecutionInfo

class PendingDecisionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATE_FIELD_NUMBER: builtins.int
    SCHEDULED_TIME_FIELD_NUMBER: builtins.int
    STARTED_TIME_FIELD_NUMBER: builtins.int
    ATTEMPT_FIELD_NUMBER: builtins.int
    ORIGINAL_SCHEDULED_TIME_FIELD_NUMBER: builtins.int
    state: global___PendingDecisionState.V = ...
    @property
    def scheduled_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def started_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    attempt: builtins.int = ...
    @property
    def original_scheduled_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        state : global___PendingDecisionState.V = ...,
        scheduled_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        started_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        attempt : builtins.int = ...,
        original_scheduled_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["original_scheduled_time",b"original_scheduled_time","scheduled_time",b"scheduled_time","started_time",b"started_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attempt",b"attempt","original_scheduled_time",b"original_scheduled_time","scheduled_time",b"scheduled_time","started_time",b"started_time","state",b"state"]) -> None: ...
global___PendingDecisionInfo = PendingDecisionInfo

class ActivityLocalDispatchInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ACTIVITY_ID_FIELD_NUMBER: builtins.int
    SCHEDULED_TIME_FIELD_NUMBER: builtins.int
    STARTED_TIME_FIELD_NUMBER: builtins.int
    SCHEDULED_TIME_OF_THIS_ATTEMPT_FIELD_NUMBER: builtins.int
    TASK_TOKEN_FIELD_NUMBER: builtins.int
    activity_id: typing.Text = ...
    @property
    def scheduled_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def started_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def scheduled_time_of_this_attempt(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    task_token: builtins.bytes = ...
    def __init__(self,
        *,
        activity_id : typing.Text = ...,
        scheduled_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        started_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        scheduled_time_of_this_attempt : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        task_token : builtins.bytes = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["scheduled_time",b"scheduled_time","scheduled_time_of_this_attempt",b"scheduled_time_of_this_attempt","started_time",b"started_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["activity_id",b"activity_id","scheduled_time",b"scheduled_time","scheduled_time_of_this_attempt",b"scheduled_time_of_this_attempt","started_time",b"started_time","task_token",b"task_token"]) -> None: ...
global___ActivityLocalDispatchInfo = ActivityLocalDispatchInfo

class ResetPoints(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POINTS_FIELD_NUMBER: builtins.int
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResetPointInfo]: ...
    def __init__(self,
        *,
        points : typing.Optional[typing.Iterable[global___ResetPointInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["points",b"points"]) -> None: ...
global___ResetPoints = ResetPoints

class ResetPointInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BINARY_CHECKSUM_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    FIRST_DECISION_COMPLETED_ID_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    EXPIRING_TIME_FIELD_NUMBER: builtins.int
    RESETTABLE_FIELD_NUMBER: builtins.int
    binary_checksum: typing.Text = ...
    run_id: typing.Text = ...
    first_decision_completed_id: builtins.int = ...
    @property
    def created_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expiring_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    resettable: builtins.bool = ...
    def __init__(self,
        *,
        binary_checksum : typing.Text = ...,
        run_id : typing.Text = ...,
        first_decision_completed_id : builtins.int = ...,
        created_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        expiring_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        resettable : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_time",b"created_time","expiring_time",b"expiring_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary_checksum",b"binary_checksum","created_time",b"created_time","expiring_time",b"expiring_time","first_decision_completed_id",b"first_decision_completed_id","resettable",b"resettable","run_id",b"run_id"]) -> None: ...
global___ResetPointInfo = ResetPointInfo
